version: '3.7'

services:
  static-page:
    container_name: static-page
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
