version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  site1:
    container_name: site1
    image: nginx:latest
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - ./site1/nginx.conf:/etc/nginx/nginx.conf
      - ./site1:/var/www/html

  site2:
    container_name: site2
    image: nginx:latest
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - ./site2/nginx.conf:/etc/nginx/nginx.conf
      - ./site2:/var/www/html
